version: 0.2

env:
variables: 
   IMAGE_TAG: "latest"
   IMAGE_REPO_NAME: "992382626730.dkr.ecr.us-east-1.amazonaws.com/away-tracker"

phases: 
  pre_build:
    commands:
    -$(aws ecr get-login --no-include-email --region us-east-1)

build:
  commands:
     - echo Build started on `date`
     - echo Building the Docker image...
     - docker build --build-arg AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
     --build-arg AWS_REGION=$AWS_REGION -t 992382626730.dkr.ecr.us-east-1.amazonaws.com/away-tracker:latest . 
post_build:
  commands:
     - echo Build completed on `date`
     - echo Pushing the Docker image...
     - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
     - printf '[{"name":"image-name","imageUri":"%s"}]' 992382626730.dkr.ecr.us-east-1.amazonaws.com/away-tracker:latest > i artifacts:
files:
-    imagedefinitions.json
-    appspec.yml
-    start-process.sh