import { AuthContextProvider } from "./context/AuthContext";
import Header from "./components/header";
import './globals.css';
import "bootstrap/dist/css/bootstrap.min.css"; // Import bootstrap CSS


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

// The Root of the DOM.
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>
          <Header />
          {children}
        </AuthContextProvider>
      </body>
    </html>
  )
}
