// 'use client';
import "bootstrap/dist/css/bootstrap.min.css"; // Import bootstrap CSS
import { AuthContextProvider } from "./context/AuthContext";
import './globals.css';

// import 'jquery/dist/jquery.js'
// import 'popper.js/dist/umd/popper.js'
// import 'bootstrap/dist/js/bootstrap.js'
// import 'bootstrap/dist/css/bootstrap.css';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <body>{children}</body> */}
      <body>
        <AuthContextProvider>
          {children}
        </AuthContextProvider>
      </body>
    </html>
  )
}
