"use client";
// import { Inter } from 'next/font/google'
// import styles from './page.module.css'
import Image from "next/image";
import "./sass/board.scss";
import { useEffect, useState } from 'react';
import { useAuthContext } from './context/AuthContext';
import { SprintView } from "./components/sprint";
import { LoadingPage } from "./components/load";


// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { user, isAdmin } = useAuthContext();
  const [loading, setLoading] = useState<boolean>(true);


  // Load for 3 seconds while user is fetched from AuthContext
  useEffect(() => {
    setTimeout(() => {
      setLoading(false);
    }, 2000); 
  }, []);


  // useEffect(() => {
  //   // import("bootstrap/dist/js/bootstrap");
  //   require("bootstrap/dist/js/bootstrap.bundle.min.js");
  // }, []);
  return (

    // <main className={styles.main}>  
    // <h1 className={inter.className}>Sprint Board</h1>
    // <main className='board'>  
    <main>
      {loading && <LoadingPage />}
      {!loading && 
        <>
          {user && <SprintView />}
          {!user && <UserLessDisplay />}
        </>

      }
      {/* {!user && <UserLessDisplay />}

      {user && <SprintView />} */}

      {/* <h1 className="display-5 fw-bold text-center">Away Project Tracker</h1> */}

    {/* <main className='d-flex flex-column'></main> */}
      {/* <h1>Sprint Board 1</h1> */}
      {/* <Header setAuthenticated={setAuthenticated} authenticated /> */}
      {/* <SprintBoard isAdmin={isAdmin}/> */}
      {/* Add peerInProgress peerCodeReview */}
    </main>
  )
}

const UserLessDisplay = () => {
  return (
    <section className={"text-center my-5 py-5"}>
      <h1 className={"text-muted alert alert-warning"}>Please <b>log in</b> <i>or</i> <b>sign up</b> to access sprints</h1>
      <Image
            src="/sprintLogo.svg"
            alt="board-logo"
            width={200}
            height={200}
            priority={true}
        />

    </section>
  )
}

// export default function Home() {
//   useEffect(() => {
//     // import("bootstrap/dist/js/bootstrap");
//     require("bootstrap/dist/js/bootstrap.bundle.min.js");
//   }, []);
//   return (
//     <div className="container p-3 vh-100">
//       <button className="btn btn-primary m-3">Sling Academy</button>
//       <button className="btn btn-warning m-3">Hello</button>

//       <div className="dropdown m-3">
//         <button
//           className="btn btn-secondary dropdown-toggle"
//           type="button"
//           data-bs-toggle="dropdown"
//           id="dropdownMenuButton1"
//           aria-expanded="false"
//         >
//           Dropdown button
//         </button>
//         <ul className="dropdown-menu" aria-labelledby="dropdownMenuButton1">
//           <li>
//             <a className="dropdown-item" href="#">
//               Option 1
//             </a>
//           </li>
//           <li>
//             <a className="dropdown-item" href="#">
//               Option 2
//             </a>
//           </li>
//           <li>
//             <a className="dropdown-item" href="#">
//               Option 3
//             </a>
//           </li>
//         </ul>
//       </div>
//     </div>
//   );
// }




// import Head from 'next/head';

// export default function Home() {
//   return (
//     <main className="d-flex flex-column min-vh-100">
//       <Header />
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="px-4 py-5 my-5 text-center flex-grow-1">
//         <h1 className="display-5 fw-bold">Next.js + Bootstrap ❤️</h1>
//         <div className="col-lg-6 mx-auto">
//           <p className="lead mb-4">
//             Quickly design and customize responsive mobile-first sites with Bootstrap, the
//             world’s most popular front-end open source toolkit, featuring Sass variables
//             and mixins, responsive grid system, extensive prebuilt components, and
//             powerful JavaScript plugins.
//           </p>
//           <div className="d-grid gap-2 d-sm-flex justify-content-sm-center">
//             <button type="button" className="btn btn-primary btn-lg px-4 gap-3">
//               Primary button
//             </button>
//             <button type="button" className="btn btn-outline-secondary btn-lg px-4">
//               Secondary
//             </button>
//           </div>
//         </div>
//       </div>
//     </main>
//   );
// }

