"use client";
// import { Inter } from 'next/font/google'
// import styles from './page.module.css'

import { Provider } from 'react-redux';
// import store from './redux/store';
import SprintBoard from './components/board'
import Header from './components/tst_header';
import { useContext, useEffect, useState } from 'react';
import { AuthContext } from './context/AuthContext';
import { isAdminUser } from './components/auth';


// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const user = useContext(AuthContext);
  const idToken = useContext(AuthContext);
  const [authenticated, setAuthenticated] = useState<boolean>(false);
  const [isAdmin, setIsAdmin] = useState<boolean>(false);

  useEffect(() => {

    isAdminUser(user).then(r => {
      console.log('page.tsx admin: ' +isAdmin)
      setIsAdmin(r)
    })
  }, [user])

  // useEffect(() => {
  //   // import("bootstrap/dist/js/bootstrap");
  //   require("bootstrap/dist/js/bootstrap.bundle.min.js");
  // }, []);
  return (

    // <main className={styles.main}>  
    // <h1 className={inter.className}>Sprint Board</h1>
    <main>  

      {/* <h1 className="display-5 fw-bold text-center">Away Project Tracker</h1> */}

    {/* <main className='d-flex flex-column'></main> */}
      {/* <h1>Sprint Board 1</h1> */}
      <Header setAuthenticated={setAuthenticated} authenticated />
      <SprintBoard peerInProgress peerCodeReview authenticated isAdmin={isAdmin}/>
    </main>
  )
}

// export default function Home() {
//   useEffect(() => {
//     // import("bootstrap/dist/js/bootstrap");
//     require("bootstrap/dist/js/bootstrap.bundle.min.js");
//   }, []);
//   return (
//     <div className="container p-3 vh-100">
//       <button className="btn btn-primary m-3">Sling Academy</button>
//       <button className="btn btn-warning m-3">Hello</button>

//       <div className="dropdown m-3">
//         <button
//           className="btn btn-secondary dropdown-toggle"
//           type="button"
//           data-bs-toggle="dropdown"
//           id="dropdownMenuButton1"
//           aria-expanded="false"
//         >
//           Dropdown button
//         </button>
//         <ul className="dropdown-menu" aria-labelledby="dropdownMenuButton1">
//           <li>
//             <a className="dropdown-item" href="#">
//               Option 1
//             </a>
//           </li>
//           <li>
//             <a className="dropdown-item" href="#">
//               Option 2
//             </a>
//           </li>
//           <li>
//             <a className="dropdown-item" href="#">
//               Option 3
//             </a>
//           </li>
//         </ul>
//       </div>
//     </div>
//   );
// }




// import Head from 'next/head';

// export default function Home() {
//   return (
//     <main className="d-flex flex-column min-vh-100">
//       <Header />
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="px-4 py-5 my-5 text-center flex-grow-1">
//         <h1 className="display-5 fw-bold">Next.js + Bootstrap ❤️</h1>
//         <div className="col-lg-6 mx-auto">
//           <p className="lead mb-4">
//             Quickly design and customize responsive mobile-first sites with Bootstrap, the
//             world’s most popular front-end open source toolkit, featuring Sass variables
//             and mixins, responsive grid system, extensive prebuilt components, and
//             powerful JavaScript plugins.
//           </p>
//           <div className="d-grid gap-2 d-sm-flex justify-content-sm-center">
//             <button type="button" className="btn btn-primary btn-lg px-4 gap-3">
//               Primary button
//             </button>
//             <button type="button" className="btn btn-outline-secondary btn-lg px-4">
//               Secondary
//             </button>
//           </div>
//         </div>
//       </div>
//     </main>
//   );
// }
